/**
 * Anonymous avatars are generated by DiceBear from a style + seed.
 * A user's avatar is stored as "<style>:<seed>" so it can be re-rendered anywhere.
 */
export const AVATAR_STYLES = ['adventurer', 'lorelei', 'notionists', 'micah', 'big-smile', 'fun-emoji'] as const;

const BACKGROUNDS = 'b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf';

export function avatarUrl(avatar: string, size = 256): string {
  const [style, seed] = avatar.includes(':') ? avatar.split(':') : ['adventurer', avatar];
  return `https://api.dicebear.com/9.x/${style}/png?seed=${encodeURIComponent(seed)}&size=${size}&backgroundColor=${BACKGROUNDS}`;
}

export function randomAvatar(): string {
  const style = AVATAR_STYLES[Math.floor(Math.random() * AVATAR_STYLES.length)];
  return `${style}:${Math.random().toString(36).slice(2, 10)}`;
}

export function generateAvatarOptions(count = 9): string[] {
  return Array.from({ length: count }, randomAvatar);
}
